kind: pipeline
build:
  image: centos:7
  commands:
    - yum install -y epel-release
    - yum install -y nodejs npm
    - npm -d install

publish:
    image: plugins/docker
    insecure: true
    registry: docker-test
    repo: docker-test
    dockerfile: Docke:rfile
    secrets: [ docker_username, docker_password ]
    tags: [ latest, 1.1 ]
