kind: pipeline
build:
  image: centos:7
  commands:
    - yum install -y epel-release
    - yum install -y nodejs npm
    - npm -d install

machine:
  node:
    version: 7.10.0

dependencies:
  pre:
    - wget https://releases.hashicorp.com/terraform/0.9.11/terraform_0.9.11_linux_amd64.zip
    - unzip terraform_0.9.11_linux_amd64.zip

test:
  override:
    - npm test

deployment:
   production:
     branch: master
     commands:
       - ./terraform plan
       - ./terraform apply


publish:
    image: plugins/docker
    insecure: true
    registry: docker-test
    repo: docker-test
    dockerfile: Docke:rfile
    secrets: [ docker_username, docker_password ]
    tags: [ latest, 1.1 ]
